name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-app-output
          path: "*.py"
          if-no-files-found: error  # Fail if no files are found

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This job runs only if the test job succeeds
    if: github.ref == 'refs/heads/main'  # Only run on main branch pushes
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: python-app-output  # Matches the name from the upload step
          path: downloaded-files/  # Directory where artifacts are downloaded

      - name: List downloaded files
        run: ls -la downloaded-files/  # Verify the files are there

      - name: Simulate deployment
        run: |
          echo "Deploying files from downloaded-files/"
          python downloaded-files/app.py  # Example: Run the downloaded app.py